tag @p remove powermaze
tag @p remove yellow_keycard
tag @p remove bridge
tag @p remove captain_1
tag @p remove captain_2
tag @p remove verification_1
tag @p remove verification_1_success
tag @p remove nyt
tag @p remove codex
tag @p remove classified
tag @p remove verification_2
tag @p remove verification_2_success